version: 0.2

env:
  parameter-store:
    RECAPTCHA_SITE_KEY: "davidshefcikcom-client-recaptcha-key"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "Installing node.js."
      - npm install --only=production
  pre_build:
    commands:
      - echo "In the pre build phase."
  build:
    commands:
      - echo "Starting build."
      - npm run build
      - echo "Done with build. Removing old package.json."
      - rm -rf package.json
      - rm -rf package-lock.json
      - rm -rf node_modules
      - echo "npm init."
      - npm init -y
      - echo "Installing express"
      - npm install express
      - echo "Done with installing. Moving on."
  post_build:
    commands:
      - echo "In the post build phase."
      
artifacts:
  files:
    - "dist/**/*"
    - ".ebextensions/**/*"
    - "server/**/*"
  discard-paths: no
