version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "Installing node.js."
      - npm install --only=production
  pre_build:
    commands:
      - echo "In the pre build phase."
  build:
    commands:
      - echo "Starting build."
      - npm run build
      - echo "Done with build."
  post_build:
    commands:
      - echo "In the post build phase."
      
artifacts:
  files:
    - "dist/*"
  discard-paths: no